### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array\(\[9, 8, 7, 6, 5, 4, 3, 2, 1, 0\]\)\).

In [28]:
import numpy as np

In [111]:
user_input = int(input('Введите целое число, лучше небольшое'))

massiv = np.arange(user_input)[::-1]

print(f'Вы ввели число {user_input}')
massiv

Вы ввели число 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [112]:
user_inp = int(input('Введите целое число, небольшое лучше'))

matrix = np.diag(np.arange(user_inp)[::-1])

print(f'Вы ввели число {user_inp}')
matrix

Вы ввели число 8


array([[7, 0, 0, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [113]:
# считаем сумму значений на диагонали
sum_elements = 0

for index in range(len(matrix)):
    sum_elements += matrix[index][index]
        
print(f'Сумма диагональных элементов равна {sum_elements}')


Сумма диагональных элементов равна 28


In [114]:
# "короткий" вариант решения

sum(matrix[index][index] for index in range(len(matrix)))

28

### Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3


In [2]:
# создаем из коэффициентов матрицу и массив
m_1 = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
m_2 = np.array([4, 12, -3])

In [29]:
from numpy import linalg

In [7]:
# получаем значения x, y, z
linalg.solve(m_1, m_2)

array([ 0.46666667,  3.84444444, -5.55555556])

In [9]:
# проверка решения
np.allclose( np.dot(m_1, linalg.solve(m_1, m_2)), m_2 )

True

### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя (виден только на скриншоте). Остальные столбцы - количество покупок категорий товаров этими пользователями. Матрица покупок по категориям в виде numpy array:

In [30]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [31]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [52]:
# определяем длину вектора нового пользователя
next_length = np.linalg.norm( next_user_stats )

# создаем пустой массив, в котором будем искать мах значение (близкое к 1)
array_cosinus = np.array([])

for user in users_stats:
    
    # для каждого user определяем длину вектора
    length = np.linalg.norm( user )

    # рассчитываем косинусное расстояние между новым и каждым user
    cosinus = np.dot( next_user_stats, user ) / (next_length * length)

    # добавляем полученное значение в массив
    array_cosinus = np.append(array_cosinus, cosinus)

In [55]:
# смотрим на полученные данные (для информации)
array_cosinus

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])

In [58]:
# для получения ID пользователя, на которого похож новый,
# определяем индекс мах значения в массиве и прибавляем 1 (индексация начинается с 0)

array_cosinus.argmax() + 1

8